name: PR Check

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - '**'
  workflow_dispatch:

jobs:
  rust-pr-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
      
      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          cache-all-crates: true
          prefix-key: "rs_cache"
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          shared-key: "share"

      - name: Setup localization runner tools
        run: cargo install --git https://github.com/StarCitizenToolBox/runner_tools.git --tag v1.0.0 localization
  
      - name: PR Check
        env:
          GH_REPO: ${{ github.repository }}
          GH_PR_NUMBER: ${{ github.event.pull_request.id }}
          GH_PR_TITLE: ${{ github.event.pull_request.title }}
        run: localization -m pr_check