name: Check Auto Release

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:
jobs:
  auto-release:
    if: github.repository == 'StarCitizenToolBox/LocalizationData'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          cache-all-crates: true
          prefix-key: "rs_cache"
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          shared-key: "share"

      - name: Setup localization runner tools
        run: cargo install --git https://github.com/StarCitizenToolBox/runner_tools.git --tag v1.0.2 localization
     
      - name: Auto Release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GH_REPO: ${{ github.repository }}
        run: localization -m auto_release